import type { Metadata } from "next";
import "./globals.css";

// import 'swiper/css';
// import 'swiper/css/navigation';
// import 'swiper/css/pagination';


export const metadata: Metadata = {
  title: "Landing Page Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-kanit">
        {children}
      </body>
    </html>
  );
}
